services:
  web-api:
    image: ${DOCKER_REGISTRY-}webapi
    container_name: web-api
    build:
      context: .
      dockerfile: Web.Api/Dockerfile
    ports:
      - 5000:8080
      - 5001:8081

  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      - POSTGRES_DB=assignment
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./.containers/db:/var/lib/postgresql/data
    ports:
      - 5432:5432