name: Publish

on:
  workflow_dispatch:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  publish:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: "8.0.x"

    - name: Restore
      run: dotnet restore ./Assignment.sln

    - name: Build
      run: dotnet build ./Assignment.sln --configuration Release --no-restore

    - name: Publish
      run: dotnet publish ./Assignment.sln --configuration Release --no-build
